# -*- coding: utf-8 -*-
"""paython basic assi=10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjviM3fgyNHITyvOyuCoQNGM0eVxanKr

1. Write a Python program to find sum of elements in list?
"""

def sum_of_elements(input_list):
    total_sum = 0
    for element in input_list:
        total_sum += element
    return total_sum

# Test the function
sample_list = [1, 2, 3, 4, 5]
result = sum_of_elements(sample_list)
print("Sum of elements in the list:", result)

"""2. Write a Python program to Multiply all numbers in the list?"""

def multiply_elements(input_list):
    result = 1
    for element in input_list:
        result *= element
    return result

# Test the function
sample_list = [1, 2, 3, 4, 5]
result = multiply_elements(sample_list)
print("Result of multiplying all numbers in the list:", result)

"""3. Write a Python program to find smallest number in a list?"""

def find_smallest_number(input_list):
    if not input_list:
        return None

    smallest = input_list[0]
    for number in input_list[1:]:
        if number < smallest:
            smallest = number
    return smallest

# Test the function
sample_list = [10, 5, 8, 2, 15, 3]
result = find_smallest_number(sample_list)
print("Smallest number in the list:", result)

"""4. Write a Python program to find largest number in a list?"""

def find_largest_number(input_list):
    if not input_list:
        return None

    largest = input_list[0]
    for number in input_list[1:]:
        if number > largest:
            largest = number
    return largest

# Test the function
sample_list = [10, 5, 8, 2, 15, 3]
result = find_largest_number(sample_list)
print("Largest number in the list:", result)

"""5. Write a Python program to find second largest number in a list?"""

def find_second_largest_number(input_list):
    if not input_list or len(input_list) < 2:
        return None

    largest = max(input_list[0], input_list[1])
    second_largest = min(input_list[0], input_list[1])

    for number in input_list[2:]:
        if number > largest:
            second_largest = largest
            largest = number
        elif number > second_largest:
            second_largest = number

    return second_largest

# Test the function
sample_list = [10, 5, 8, 2, 15, 3]
result = find_second_largest_number(sample_list)
print("Second largest number in the list:", result)

"""6. Write a Python program to find N largest elements from a list?"""

def find_n_largest_elements(input_list, n):
    if not input_list or n <= 0:
        return []

    sorted_list = sorted(input_list, reverse=True)
    n_largest_elements = sorted_list[:n]
    return n_largest_elements

# Test the function
sample_list = [10, 5, 8, 2, 15, 3]
N = 3
result = find_n_largest_elements(sample_list, N)
print(f"{N} largest elements in the list:", result)

"""7. Write a Python program to print even numbers in a list?"""

def print_even_numbers(input_list):
    even_numbers = [num for num in input_list if num % 2 == 0]
    print("Even numbers in the list:", even_numbers)

# Test the function
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print_even_numbers(sample_list)

"""8. Write a Python program to print odd numbers in a List?"""

def print_odd_numbers(input_list):
    odd_numbers = [num for num in input_list if num % 2 != 0]
    print("Odd numbers in the list:", odd_numbers)

# Test the function
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print_odd_numbers(sample_list)

"""9. Write a Python program to Remove empty List from List?"""

def remove_empty_lists(input_list):
    return [item for item in input_list if item]

# Test the function
sample_list = [1, [], 2, [], [], 3, [], 4, 5]
result = remove_empty_lists(sample_list)
print("List with empty lists removed:", result)

"""10. Write a Python program to Cloning or Copying a list?"""

def clone_list(input_list):
    return input_list[:]

# Test the function
sample_list = [1, 2, 3, 4, 5]
cloned_list = clone_list(sample_list)
print("Original List:", sample_list)
print("Cloned List:", cloned_list)

def clone_list(input_list):
    return list(input_list)

# Test the function
sample_list = [1, 2, 3, 4, 5]
cloned_list = clone_list(sample_list)
print("Original List:", sample_list)
print("Cloned List:", cloned_list)

def clone_list(input_list):
    return input_list.copy()

# Test the function
sample_list = [1, 2, 3, 4, 5]
cloned_list = clone_list(sample_list)
print("Original List:", sample_list)
print("Cloned List:", cloned_list)

"""11. Write a Python program to Count occurrences of an element in a list?"""

def count_occurrences(input_list, element):
    count = 0
    for item in input_list:
        if item == element:
            count += 1
    return count

# Test the function
sample_list = [1, 2, 2, 3, 4, 2, 5]
element_to_count = 2
result = count_occurrences(sample_list, element_to_count)
print(f"Number of occurrences of {element_to_count} in the list:", result)