# -*- coding: utf-8 -*-
"""paython basics assi=7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15W04E-5rABCDkOf9Bqnn1YfNaLi2SB3d

1. Write a Python Program to find sum of array?
"""

def array_sum(arr):
    total = 0
    for num in arr:
        total += num
    return total

try:
    # Input the elements of the array separated by spaces
    elements = input("Enter the elements of the array separated by spaces: ")
    arr = list(map(int, elements.split()))

    result = array_sum(arr)
    print(f"The sum of the array is: {result}")
except ValueError:
    print("Invalid input. Please enter valid integer values separated by spaces.")

"""2. Write a Python Program to find largest element in an array?"""

def find_largest_element(arr):
    if not arr:
        return "Array is empty."

    largest = arr[0]
    for num in arr[1:]:
        if num > largest:
            largest = num
    return largest

try:
    # Input the elements of the array separated by spaces
    elements = input("Enter the elements of the array separated by spaces: ")
    arr = list(map(int, elements.split()))

    result = find_largest_element(arr)
    print(f"The largest element in the array is: {result}")
except ValueError:
    print("Invalid input. Please enter valid integer values separated by spaces.")

"""3. Write a Python Program for array rotation?"""

def rotate_array(arr, k):
    """
    Rotate an array 'arr' by 'k' positions to the right.

    Parameters:
    arr (list): The input array to be rotated.
    k (int): The number of positions to rotate the array.

    Returns:
    list: The rotated array.
    """
    n = len(arr)
    k = k % n  # To handle cases where k > n

    # If k is 0 or equal to the array size, no rotation needed
    if k == 0 or k == n:
        return arr

    rotated = []
    for i in range(n - k, n):
        rotated.append(arr[i])

    for i in range(n - k):
        rotated.append(arr[i])

    return rotated


# Example usage
if __name__ == "__main__":
    input_array = [1, 2, 3, 4, 5]
    rotate_by = 2
    rotated_array = rotate_array(input_array, rotate_by)
    print("Original Array:", input_array)
    print("Rotated Array:", rotated_array)

"""4. Write a Python Program to Split the array and add the first part to the end?"""

def split_and_add(arr, split_index):
    """
    Split the array 'arr' into two parts at the given 'split_index' and add the first part to the end.

    Parameters:
    arr (list): The input array to be split and added.
    split_index (int): The index at which the array is split.

    Returns:
    list: The modified array after splitting and adding.
    """
    n = len(arr)

    if split_index < 0 or split_index >= n:
        raise ValueError("Invalid split_index. It should be within the range of the array.")

    return arr[split_index:] + arr[:split_index]


# Example usage
if __name__ == "__main__":
    input_array = [1, 2, 3, 4, 5]
    split_index = 2
    modified_array = split_and_add(input_array, split_index)
    print("Original Array:", input_array)
    print("Modified Array:", modified_array)

"""5. Write a Python Program to check if given array is Monotonic?"""

def is_monotonic(arr):
    """
    Check if the given array 'arr' is monotonic.

    Parameters:
    arr (list): The input array to check.

    Returns:
    bool: True if the array is monotonic, False otherwise.
    """
    increasing = decreasing = True

    for i in range(1, len(arr)):
        if arr[i] > arr[i - 1]:
            decreasing = False
        elif arr[i] < arr[i - 1]:
            increasing = False

    return increasing or decreasing


# Example usage
if __name__ == "__main__":
    input_array1 = [1, 2, 3, 4, 5]
    input_array2 = [5, 4, 3, 2, 1]
    input_array3 = [1, 2, 2, 3, 4]

    print("Is input_array1 monotonic?", is_monotonic(input_array1))
    print("Is input_array2 monotonic?", is_monotonic(input_array2))
    print("Is input_array3 monotonic?", is_monotonic(input_array3))